export const GET_POKEMON_LIST_SUCCESS = "GET_POKEMON_LIST_SUCCESS";
export const GET_POKEMON_DETAILS_SUCCESS = "GET_POKEMON_DETAILS_SUCCESS";
export const GET_IMAGE_URL_SUCCESS = "GET_IMAGE_URL_SUCCESS";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const SET_CAUGHT_POKEMON = "SET_CAUGHT_POKEMON";
export const GET_CAUGHT_POKEMON_LIST = "GET_CAUGHT_POKEMON_LIST";
export const SET_RELEASE_POKEMON = "SET_RELEASE_POKEMON";

export const GET_POKEMON_LIST_FAIL = "GET_POKEMON_LIST_FAIL";
export const GET_POKEMON_DETAILS_FAIL = "GET_POKEMON_DETAILS_FAIL";
export const GET_IMAGE_URL_FAIL = "GET_IMAGE_URL_FAIL";
export const GET_POKEMON_FAIL = "GET_POKEMON_FAIL";
export const SET_CAUGHT_POKEMON_FAIL = "SET_CAUGHT_POKEMON_FAIL";
